import { z } from "zod";
import { D, money, sum, allocate } from "./money";
import { accountNames, type Actor, type Workspace, type Document, type Line, type JournalLine, type CommissionPlan } from "./types";

export const commandSchema=z.object({type:z.enum(["create_document","submit_document","convert_document","return_document","create_receipt","update_cheque","approve_commission","create_payroll","update_payroll","create_shipment","add_shipment_cost","allocate_shipment","bulk_stock_increase","stock_transfer","stock_adjust","create_journal","reverse_journal","set_period","save_party","save_item","save_employee","save_plan","save_settings","bank_import","bank_match","follow_up","import_records"]),idempotencyKey:z.string().min(8).max(100),payload:z.record(z.string(),z.unknown())});
export type Command=z.infer<typeof commandSchema>;
const id=()=>crypto.randomUUID();
const today=()=>new Date().toISOString().slice(0,10);
const s=(p:Record<string,unknown>,k:string,def?:string)=>z.string().max(2000).parse(p[k]??def);
const date=(v:unknown)=>z.iso.date().parse(v);
const decimal=z.union([z.string(),z.number()]).transform(v=>String(v)).refine(v=>{try{return D(v).isFinite()&&D(v).abs().lt("1000000000000")}catch{return false}},"Enter a valid number below one trillion.");
const pos=decimal.refine(v=>D(v).gt(0),"Amount must be greater than zero.");
const nonneg=decimal.refine(v=>D(v).gte(0),"Amount cannot be negative.");
const pct=nonneg.refine(v=>D(v).lte(100),"Percentage cannot exceed 100.");
const allow:Record<string,string[]>={
 create_document:["Accountant","Sales Manager","Salesperson","Warehouse Manager"],submit_document:["Accountant","Sales Manager","Warehouse Manager"],convert_document:["Accountant","Sales Manager","Salesperson","Warehouse Manager"],return_document:["Accountant","Sales Manager"],
 create_receipt:["Accountant","Recovery Officer"],update_cheque:["Accountant","Recovery Officer"],approve_commission:["Accountant","Sales Manager"],create_payroll:["Accountant","Payroll Administrator"],update_payroll:["Accountant","Payroll Administrator"],
 create_shipment:["Accountant","Warehouse Manager"],add_shipment_cost:["Accountant"],allocate_shipment:["Accountant"],bulk_stock_increase:["Accountant","Warehouse Manager"],stock_transfer:["Warehouse Manager","Accountant"],stock_adjust:["Warehouse Manager","Accountant"],create_journal:["Accountant"],reverse_journal:["Accountant"],set_period:["Accountant"],save_party:["Accountant","Sales Manager"],save_item:["Warehouse Manager","Accountant"],save_employee:["Payroll Administrator"],save_plan:["Sales Manager"],save_settings:[],bank_import:["Accountant"],bank_match:["Accountant"],follow_up:["Recovery Officer","Sales Manager"],import_records:["Accountant"]
};
export function canRun(role:string,action:string){return role==="Owner"||(allow[action]??[]).includes(role)}
function requireOpen(w:Workspace,d:string){date(d);if(w.periods.some(p=>p.month===d.slice(0,7)&&p.locked))throw new Error(`Accounting period ${d.slice(0,7)} is locked.`);}
function warehouseAccess(w:Workspace,a:Actor,warehouse:string){const r=w.warehouses.find(x=>x.id===warehouse);if(!r)throw new Error("Warehouse not found.");if(a.branchIds.length&&!a.branchIds.includes(r.branchId))throw new Error("This warehouse is outside your permitted branches.");}
function found<T extends {id:string}>(items:T[],key:string,label:string):T{const r=items.find(x=>x.id===key);if(!r)throw new Error(`${label} not found.`);return r;}
export function stock(w:Workspace,itemId:string,warehouseId?:string){const moves=w.stockMoves.filter(m=>m.itemId===itemId&&(!warehouseId||m.warehouseId===warehouseId));const quantity=sum(moves.map(m=>m.quantity));const value=sum(moves.map(m=>m.value));return {quantity:money(quantity),value:money(value),average:money(quantity.gt(0)?value.div(quantity):0)};}
export function accountBalance(w:Workspace,code:string){return money(sum(w.journals.filter(j=>j.status==="posted").flatMap(j=>j.lines.filter(l=>l.account===code).map(l=>D(l.debit).minus(l.credit)))));}
export function outstanding(d:Document){return money(D(d.total).minus(d.paid).minus(d.returned));}
export function commissionTotals(w:Workspace,employeeId?:string){const list=w.commissions.filter(c=>!employeeId||c.employeeId===employeeId);return {earned:money(sum(list.map(c=>c.earned))),released:money(sum(list.map(c=>c.released))),paid:money(sum(list.map(c=>c.paid))),unreleased:money(sum(list.map(c=>D.max(0,D(c.earned).minus(c.released))))),unpaid:money(sum(list.map(c=>D.max(0,D(c.released).minus(c.paid))))),recoverable:money(sum(list.map(c=>D.max(0,D(c.paid).minus(c.released)))))};}
export function summary(w:Workspace){const invoices=w.documents.filter(d=>d.kind==="sales_invoice"&&d.status==="submitted");return {sales:money(D(accountBalance(w,"4000")).negated()),cash:accountBalance(w,"1000"),receivables:accountBalance(w,"1100"),payables:money(D(accountBalance(w,"2000")).negated()),inventory:accountBalance(w,"1200"),collections:money(sum(w.receipts.filter(r=>r.status==="cleared"&&w.parties.find(p=>p.id===r.partyId)?.type==="customer").map(r=>r.amount))),commission:commissionTotals(w),invoices:invoices.length,margin:money(D(accountBalance(w,"4000")).negated().minus(accountBalance(w,"5000")))};}
export function postJournal(w:Workspace,sourceId:string,memo:string,lines:JournalLine[],d=today(),reversalOf?:string){
 requireOpen(w,d);const cleaned=lines.filter(l=>!D(l.debit).isZero()||!D(l.credit).isZero()).map(l=>({...l,debit:money(l.debit),credit:money(l.credit)}));
 if(!cleaned.length)return;
 if(cleaned.some(l=>!accountNames[l.account]||D(l.debit).lt(0)||D(l.credit).lt(0)||(D(l.debit).gt(0)&&D(l.credit).gt(0))))throw new Error("Journal accounts and amounts must be valid.");
 if(!sum(cleaned.map(l=>l.debit)).eq(sum(cleaned.map(l=>l.credit))))throw new Error("Journal debits and credits must balance.");
 if(w.journals.some(j=>j.sourceId===sourceId))throw new Error("This source has already been posted.");
 const j={id:id(),number:`JV-${String(w.journals.length+1).padStart(5,"0")}`,sourceId,date:d,memo,status:"posted" as const,lines:cleaned,...(reversalOf?{reversalOf}:{})};w.journals.push(j);return j;
}
const jl=(account:string,debit:string|number=0,credit:string|number=0):JournalLine=>({account,debit:money(debit),credit:money(credit)});
function move(w:Workspace,itemId:string,warehouseId:string,quantity:string,value:string,sourceId:string,d:string,type:string){const st=stock(w,itemId,warehouseId);if(D(st.quantity).plus(quantity).lt(0))throw new Error(`Insufficient stock for ${found(w.items,itemId,"Product").name} in ${found(w.warehouses,warehouseId,"Warehouse").name}. Requested: ${D(quantity).abs().toString()}, available: ${D(st.quantity).toString()}.`);w.stockMoves.push({id:id(),itemId,warehouseId,quantity:money(quantity),value:money(value),sourceId,date:d,type});}
function lineTotal(l:Line){return D(l.quantity).mul(l.price).mul(D(100).minus(l.discount)).div(100)}
const lineInput=z.object({itemId:z.string(),quantity:pos,price:nonneg,discount:pct.default("0"),taxRate:pct.default("18"),employeeId:z.string().default(""),splits:z.array(z.object({employeeId:z.string(),share:pct})).default([])});
const kinds=["quotation","sales_order","delivery","sales_invoice","purchase_order","goods_receipt","supplier_invoice"] as const;
function createDocument(w:Workspace,p:Record<string,unknown>,a:Actor){
 const input=z.object({kind:z.enum(kinds),partyId:z.string(),warehouseId:z.string(),date:z.iso.date(),dueDate:z.iso.date(),currency:z.enum(["PKR","USD","CNY"]).default("PKR"),fxRate:pos.default("1"),lines:z.array(lineInput).min(1).max(100),notes:z.string().max(2000).default(""),parentId:z.string().optional(),creditOverride:z.string().max(500).optional()}).parse(p);
 const sales=["quotation","sales_order","delivery","sales_invoice"].includes(input.kind);
 if(["Salesperson","Sales Manager"].includes(a.role)&&!sales)throw new Error("Your role cannot create purchase documents.");
 if(a.role==="Warehouse Manager"&&!["delivery","goods_receipt"].includes(input.kind))throw new Error("Warehouse users can create receipts and deliveries only.");
 if(input.currency!=="PKR"&&sales)throw new Error("Sales use the company's PKR base currency.");
 if(input.currency==="PKR"&&!D(input.fxRate).eq(1))throw new Error("PKR exchange rate must be 1.");
 if(found(w.parties,input.partyId,"Party").type!==(sales?"customer":"supplier"))throw new Error("Select the appropriate customer or supplier.");
 warehouseAccess(w,a,input.warehouseId);requireOpen(w,input.date);
 if(new Set(input.lines.map(l=>l.itemId)).size!==input.lines.length)throw new Error("Use one line per product.");
 const lines=input.lines.map(l=>{found(w.items,l.itemId,"Product");if(sales&&l.employeeId)found(w.employees,l.employeeId,"Employee");if(a.role==="Salesperson"&&l.employeeId!==a.employeeId)throw new Error("Salespeople can create their own sales only.");if(l.splits.length){if(!sum(l.splits.map(x=>x.share)).eq(100))throw new Error("Commission splits must total 100%.");l.splits.forEach(x=>found(w.employees,x.employeeId,"Employee"));}return {...l,id:id(),cost:"0.0000",returned:"0.0000"};});
 const net=sum(lines.map(lineTotal));const tax=sum(lines.map(l=>lineTotal(l).mul(l.taxRate).div(100)));
 const prefix:Record<string,string>={quotation:"QUO",sales_order:"SO",delivery:"DN",sales_invoice:"INV",purchase_order:"PO",goods_receipt:"GRN",supplier_invoice:"BILL"};
 const doc:Document={...input,id:id(),number:`${prefix[input.kind]}-2026-${String(w.documents.filter(d=>d.kind===input.kind).length+1).padStart(4,"0")}`,status:"draft",lines,net:money(net),tax:money(tax),total:money(net.plus(tax)),paid:"0.0000",returned:"0.0000"};
 if(input.parentId){const parent=found(w.documents,input.parentId,"Source document");if(parent.status!=="submitted")throw new Error("Submit the source document first.");if(parent.partyId!==doc.partyId||parent.warehouseId!==doc.warehouseId||parent.currency!==doc.currency)throw new Error("Source party, warehouse and currency must match.");const next:Record<string,string>={quotation:"sales_order",sales_order:"delivery",delivery:"sales_invoice",purchase_order:"goods_receipt",goods_receipt:"supplier_invoice"};if(next[parent.kind]!==doc.kind)throw new Error("Invalid document conversion.");for(const l of doc.lines){const original=parent.lines.find(x=>x.itemId===l.itemId);const used=sum(w.documents.filter(x=>x.parentId===parent.id&&x.status!=="cancelled").flatMap(x=>x.lines.filter(y=>y.itemId===l.itemId).map(y=>y.quantity)));if(!original||used.plus(l.quantity).gt(original.quantity))throw new Error("Converted quantity exceeds the remaining source quantity.");l.cost=original.cost;}}
 w.documents.push(doc);return doc;
}
function commissionAmount(plan:CommissionPlan,base:string,quantity:string,category:string,customerClass:string){
 if(plan.type==="per_unit")return D(quantity).mul(plan.rate);
 if(plan.type==="tiered"){const tiers=[...plan.tiers].sort((a,b)=>D(a.threshold).cmp(b.threshold));return sum(tiers.map((t,i)=>D.max(0,D.min(base,tiers[i+1]?.threshold??base).minus(t.threshold)).mul(t.rate).div(100)));}
 const rate=plan.type==="category"?(plan.categoryRates[category]??plan.rate):plan.type==="customer_class"?(plan.classRates[customerClass]??plan.rate):plan.rate;return D(base).mul(rate).div(100);
}
function accrue(w:Workspace,doc:Document){const plan=w.plans.find(p=>p.effectiveFrom<=doc.date&&p.effectiveTo>=doc.date);if(!plan)return;let expense=D(0);const party=found(w.parties,doc.partyId,"Customer");for(const l of doc.lines){if(!l.employeeId&&!l.splits.length)continue;const item=found(w.items,l.itemId,"Item");const base=lineTotal(l);const splits=l.splits.length?l.splits:[{employeeId:l.employeeId,share:"100"}];const total=commissionAmount(plan,money(base),l.quantity,item.category,party.customerClass);const shares=allocate(money(total),splits.map(x=>x.share));splits.forEach((split,i)=>{let amount=D(shares[i]);const previous=sum(w.commissions.filter(c=>c.employeeId===split.employeeId&&w.documents.find(d=>d.id===c.invoiceId)?.date.slice(0,7)===doc.date.slice(0,7)).map(c=>c.eligibleBase));if(D(plan.target).gt(0)&&previous.plus(base.mul(split.share).div(100)).gte(plan.target))amount=amount.mul(plan.multiplier);const c={id:id(),invoiceId:doc.id,lineId:l.id,employeeId:split.employeeId,planSnapshot:structuredClone(plan),eligibleBase:money(base.mul(split.share).div(100)),earned:money(amount),released:"0.0000",paid:"0.0000",approved:false};w.commissions.push(c);w.commissionMovements.push({id:id(),commissionId:c.id,sourceId:doc.id,date:doc.date,type:"accrued",amount:c.earned,note:`${doc.number} · ${item.category}`});expense=expense.plus(c.earned);});}postJournal(w,`${doc.id}:commission`,`Commission accrued · ${doc.number}`,[jl("5100",money(expense)),jl("2200",0,money(expense))],doc.date);}
function updateRelease(w:Workspace,doc:Document,sourceId:string,d:string){const remaining=D(doc.total).minus(doc.returned);const ratio=remaining.gt(0)?D.min(1,D(doc.paid).div(remaining)):D(0);for(const c of w.commissions.filter(c=>c.invoiceId===doc.id)){const next=D(c.earned).mul(ratio).toDecimalPlaces(4);const delta=next.minus(c.released);if(!delta.isZero()){w.commissionMovements.push({id:id(),commissionId:c.id,sourceId,date:d,type:delta.gt(0)?"released":"release_reversed",amount:money(delta.abs()),note:"Cleared payment / return allocation"});c.released=money(next);c.approved=false;}}}
function submit(w:Workspace,doc:Document,a:Actor){if(doc.status!=="draft")throw new Error("Only draft documents can be submitted.");warehouseAccess(w,a,doc.warehouseId);requireOpen(w,doc.date);
 if(a.role==="Salesperson")throw new Error("Sales documents require manager approval.");if(a.role==="Warehouse Manager"&&!["delivery","goods_receipt"].includes(doc.kind))throw new Error("Your role can submit warehouse documents only.");if(a.role==="Sales Manager"&&!["quotation","sales_order","delivery","sales_invoice"].includes(doc.kind))throw new Error("Your role can submit sales documents only.");
 const party=found(w.parties,doc.partyId,"Party");const debitLines:JournalLine[]=[];let cost=D(0);const fromDelivery=doc.kind==="sales_invoice"&&w.documents.find(x=>x.id===doc.parentId)?.kind==="delivery";
 if(doc.kind==="sales_invoice"){const exposure=sum(w.documents.filter(x=>x.partyId===doc.partyId&&x.kind==="sales_invoice"&&x.status==="submitted").map(outstanding));if(exposure.plus(doc.total).gt(party.creditLimit)){if(a.role!=="Owner"||!doc.creditOverride?.trim())throw new Error("Customer credit limit exceeded. An owner must enter an override reason.");}doc.taxSnapshot={registered:party.registered,taxId:party.taxId,policy:"Configured demonstration tax rates; not statutory advice"};}
 if(doc.kind==="delivery"||(doc.kind==="sales_invoice"&&!fromDelivery)){for(const l of doc.lines){const balance=stock(w,l.itemId,doc.warehouseId);l.cost=balance.average;const value=D(l.quantity).mul(l.cost).toDecimalPlaces(4);move(w,l.itemId,doc.warehouseId,money(D(l.quantity).negated()),money(value.negated()),doc.id,doc.date,"sale");cost=cost.plus(value);}debitLines.push(jl("5000",money(cost)),jl("1200",0,money(cost)));}
 if(doc.kind==="sales_invoice")debitLines.push(jl("1100",doc.total),jl("4000",0,doc.net),jl("2100",0,doc.tax));
 if(doc.kind==="goods_receipt"||(doc.kind==="supplier_invoice"&&!doc.parentId)){for(const l of doc.lines){const value=lineTotal(l).mul(doc.fxRate).toDecimalPlaces(4);l.cost=money(value.div(l.quantity));move(w,l.itemId,doc.warehouseId,l.quantity,money(value),doc.id,doc.date,"purchase");cost=cost.plus(value);}if(doc.kind==="goods_receipt")debitLines.push(jl("1200",money(cost)),jl("2010",0,money(cost)));}
 if(doc.kind==="supplier_invoice"){debitLines.push(jl(doc.parentId?"2010":"1200",money(D(doc.net).mul(doc.fxRate))),jl("1300",money(D(doc.tax).mul(doc.fxRate))),jl("2000",0,money(D(doc.total).mul(doc.fxRate))));}
 postJournal(w,doc.id,`${doc.kind.replaceAll("_"," ")} · ${doc.number}`,debitLines,doc.date);doc.status="submitted";
 if(doc.kind==="sales_invoice")accrue(w,doc);
}
function returnDoc(w:Workspace,p:Record<string,unknown>,a:Actor){const original=found(w.documents,s(p,"id"),"Invoice");if(original.status!=="submitted"||!["sales_invoice","supplier_invoice"].includes(original.kind))throw new Error("Select a submitted sales or supplier invoice.");const d=date(p.date??today());warehouseAccess(w,a,original.warehouseId);requireOpen(w,d);const selected=z.array(z.object({lineId:z.string(),quantity:pos})).min(1).parse(p.lines);if(new Set(selected.map(x=>x.lineId)).size!==selected.length)throw new Error("Duplicate return line.");let net=D(0),tax=D(0),cost=D(0),commission=D(0);const source=id();const lines:Line[]=[];
 for(const entry of selected){const l=found(original.lines,entry.lineId,"Invoice line");if(D(l.returned).plus(entry.quantity).gt(l.quantity))throw new Error("Return exceeds the unreturned quantity.");const n=lineTotal(l).mul(entry.quantity).div(l.quantity).toDecimalPlaces(4);const t=n.mul(l.taxRate).div(100).toDecimalPlaces(4);const c=D(l.cost).mul(entry.quantity).toDecimalPlaces(4);net=net.plus(n);tax=tax.plus(t);cost=cost.plus(c);l.returned=money(D(l.returned).plus(entry.quantity));lines.push({...l,id:id(),quantity:entry.quantity,returned:"0.0000"});const isSale=original.kind==="sales_invoice";move(w,l.itemId,original.warehouseId,money(D(entry.quantity).mul(isSale?1:-1)),money(c.mul(isSale?1:-1)),source,d,"return");if(isSale){for(const acc of w.commissions.filter(x=>x.lineId===l.id)){const originalEarned=sum(w.commissionMovements.filter(m=>m.commissionId===acc.id&&m.type==="accrued").map(m=>m.amount));const newEarned=originalEarned.mul(D(l.quantity).minus(l.returned)).div(l.quantity).toDecimalPlaces(4);const reduction=D(acc.earned).minus(newEarned);acc.earned=money(newEarned);acc.approved=false;commission=commission.plus(reduction);w.commissionMovements.push({id:id(),commissionId:acc.id,sourceId:source,date:d,type:"entitlement_adjusted",amount:money(reduction.negated()),note:"Return reduces earned commission"});}}}
 const total=net.plus(tax);original.returned=money(D(original.returned).plus(total));const kind=original.kind==="sales_invoice"?"credit_note":"supplier_return";const credit:Document={...structuredClone(original),id:source,number:`${kind==="credit_note"?"CN":"PR"}-2026-${String(w.documents.filter(x=>x.kind===kind).length+1).padStart(4,"0")}`,kind,date:d,status:"submitted",parentId:original.id,lines,net:money(net),tax:money(tax),total:money(total),returned:"0.0000",paid:"0.0000",notes:s(p,"reason","Goods returned")};w.documents.push(credit);
 if(kind==="credit_note"){postJournal(w,source,`Credit note · ${original.number}`,[jl("4000",money(net)),jl("2100",money(tax)),jl("1100",0,money(total)),jl("1200",money(cost)),jl("5000",0,money(cost)),jl("2200",money(commission)),jl("5100",0,money(commission))],d);updateRelease(w,original,source,d);}
 else {const baseNet=net.mul(original.fxRate),baseTax=tax.mul(original.fxRate),variance=baseNet.minus(cost);postJournal(w,source,`Supplier return · ${original.number}`,[jl("2000",money(baseNet.plus(baseTax))),jl("1300",0,money(baseTax)),jl("1200",0,money(cost)),...(variance.gte(0)?[jl("5300",0,money(variance))]:[jl("5300",money(variance.negated()))])],d);}
 return source;
}
function clearReceipt(w:Workspace,r:Workspace["receipts"][number],d:string){requireOpen(w,d);const party=found(w.parties,r.partyId,"Party");let baseAmount=D(0);for(const allocation of r.allocations){const doc=found(w.documents,allocation.invoiceId,"Invoice");if(doc.status!=="submitted"||doc.partyId!==party.id||doc.kind!==(party.type==="customer"?"sales_invoice":"supplier_invoice"))throw new Error("Receipt must reference submitted invoices for the same party.");if(D(allocation.amount).gt(outstanding(doc)))throw new Error("Allocation exceeds the invoice's outstanding balance.");doc.paid=money(D(doc.paid).plus(allocation.amount));baseAmount=baseAmount.plus(D(allocation.amount).mul(doc.fxRate));if(party.type==="customer")updateRelease(w,doc,r.id,d);}
 const amount=D(r.amount);const variance=amount.minus(baseAmount);postJournal(w,`${r.id}:cleared`,`${party.type==="customer"?"Customer receipt":"Supplier payment"} · ${r.number}`,party.type==="customer"?[jl("1000",r.amount),jl("1100",0,r.amount)]:[jl("2000",money(baseAmount)),jl("1000",0,r.amount),...(variance.gte(0)?[jl("5400",money(variance))]:[jl("5400",0,money(variance.negated()))])],d);r.status="cleared";
}
function payroll(w:Workspace,p:Record<string,unknown>){const month=z.string().regex(/^\d{4}-(0[1-9]|1[0-2])$/).parse(p.month);if(w.payrolls.some(x=>x.month===month))throw new Error("A payroll run already exists for this month.");const d=date(p.date??`${month}-28`);requireOpen(w,d);const rows=w.employees.filter(e=>e.active).map(e=>{const available=w.commissions.filter(c=>c.employeeId===e.id&&c.approved&&D(c.released).gt(c.paid)&&!w.payrolls.some(pr=>pr.lines.some(l=>l.commissionIds.includes(c.id))));const amounts=Object.fromEntries(available.map(c=>[c.id,money(D(c.released).minus(c.paid))]));const comm=sum(Object.values(amounts));const basic=D(e.salary).mul(e.attendance).div(30).toDecimalPlaces(4);const gross=basic.plus(e.allowance);const ee=D(w.settings.eobiBase).mul(w.settings.employeeEobi).div(100).toDecimalPlaces(4);const er=D(w.settings.eobiBase).mul(w.settings.employerEobi).div(100).toDecimalPlaces(4);const tax=gross.plus(comm).mul(w.settings.incomeTaxRate).div(100).toDecimalPlaces(4);const net=gross.plus(comm).minus(e.deduction).minus(ee).minus(tax);if(net.lt(0))throw new Error(`Deductions exceed earnings for ${e.name}.`);return {employeeId:e.id,basic:money(basic),allowance:e.allowance,commission:money(comm),deduction:e.deduction,employeeEobi:money(ee),employerEobi:money(er),incomeTax:money(tax),net:money(net),commissionIds:available.map(c=>c.id),commissionAmounts:amounts};});if(!rows.length)throw new Error("Add active employees before creating payroll.");const pr={id:id(),number:`PAY-${month}`,month,date:d,status:"draft" as const,lines:rows,total:money(sum(rows.map(l=>l.net)))};w.payrolls.push(pr);return pr.id;}

export function execute(input:Workspace,raw:unknown,actor:Actor):{workspace:Workspace;recordId:string;message:string}{
 const command=commandSchema.parse(raw);if(!canRun(actor.role,command.type))throw new Error("Your role does not permit this action.");if(input.operations.includes(command.idempotencyKey))return {workspace:input,recordId:"",message:"This operation was already completed."};
 const w=structuredClone(input);const p=command.payload;let result="";let message="Changes saved.";
 switch(command.type){
 case "create_document":result=createDocument(w,p,actor).id;message="Draft saved. Review and submit to post it.";break;
 case "submit_document":{const doc=found(w.documents,s(p,"id"),"Document");submit(w,doc,actor);result=doc.id;message=`${doc.number} submitted. Related balances updated.`;break;}
 case "convert_document":{const source=found(w.documents,s(p,"id"),"Source document");const next:Record<string,string>={quotation:"sales_order",sales_order:"delivery",delivery:"sales_invoice",purchase_order:"goods_receipt",goods_receipt:"supplier_invoice"};if(!next[source.kind])throw new Error("This document cannot be converted.");const lines=source.lines.map(l=>{const used=sum(w.documents.filter(d=>d.parentId===source.id&&d.status!=="cancelled").flatMap(d=>d.lines.filter(x=>x.itemId===l.itemId).map(x=>x.quantity)));const quantity=money(D(l.quantity).minus(used));return {...l,quantity};}).filter(l=>D(l.quantity).gt(0));result=createDocument(w,{...source,kind:next[source.kind],parentId:source.id,lines:p.lines??lines,date:p.date??today()},actor).id;message="Next document created as a draft.";break;}
 case "return_document":result=returnDoc(w,p,actor);message="Return posted. Stock, balances and commission updated.";break;
 case "create_receipt":{const r=z.object({partyId:z.string(),date:z.iso.date(),amount:pos,method:z.enum(["bank","cash","cheque"]),chequeNo:z.string().max(100).default(""),dueDate:z.iso.date(),allocations:z.array(z.object({invoiceId:z.string(),amount:pos})).min(1),employeeId:z.string().default(""),note:z.string().max(1000).default("")}).parse(p);const party=found(w.parties,r.partyId,"Party");if(party.type==="supplier"&&actor.role==="Recovery Officer")throw new Error("Recovery officers cannot pay suppliers.");if(new Set(r.allocations.map(x=>x.invoiceId)).size!==r.allocations.length)throw new Error("Duplicate allocation.");r.allocations.forEach(x=>{const doc=found(w.documents,x.invoiceId,"Invoice");warehouseAccess(w,actor,doc.warehouseId);if(doc.partyId!==r.partyId||doc.status!=="submitted"||D(x.amount).gt(outstanding(doc)))throw new Error("Invalid invoice allocation.");});if(party.type==="customer"&&!sum(r.allocations.map(x=>x.amount)).eq(r.amount))throw new Error("Allocations must equal the receipt amount.");requireOpen(w,r.date);if(r.method==="cheque"&&!r.chequeNo.trim())throw new Error("Enter the cheque number.");const receipt={...r,id:id(),number:`REC-${String(w.receipts.length+1).padStart(4,"0")}`,status:"received" as const};w.receipts.push(receipt);if(r.method!=="cheque")clearReceipt(w,receipt,r.date);result=receipt.id;message=r.method==="cheque"?"Cheque recorded. Commission releases only on clearance.":"Payment posted and allocated.";break;}
 case "update_cheque":{const r=found(w.receipts,s(p,"id"),"Cheque");if(r.method!=="cheque")throw new Error("This payment is not a cheque.");const next=z.enum(["deposited","cleared","bounced"]).parse(p.status);const d=date(p.date??today());requireOpen(w,d);r.allocations.forEach(x=>warehouseAccess(w,actor,found(w.documents,x.invoiceId,"Invoice").warehouseId));if(next==="deposited"&&r.status==="received")r.status=next;else if(next==="cleared"&&r.status==="deposited")clearReceipt(w,r,d);else if(next==="bounced"&&["received","deposited","cleared"].includes(r.status)){if(r.status==="cleared"){const original=w.journals.find(j=>j.sourceId===`${r.id}:cleared`);if(!original)throw new Error("Original payment posting missing.");postJournal(w,`${r.id}:bounce`,"Cheque dishonoured",original.lines.map(l=>jl(l.account,l.credit,l.debit)),d,original.id);for(const alloc of r.allocations){const doc=found(w.documents,alloc.invoiceId,"Invoice");doc.paid=money(D(doc.paid).minus(alloc.amount));updateRelease(w,doc,r.id,d);}}r.status="bounced";}else throw new Error("Invalid cheque transition.");result=r.id;message=`Cheque ${next}.`;break;}
 case "approve_commission":{const ids=z.array(z.string()).min(1).parse(p.ids);for(const key of ids){const c=found(w.commissions,key,"Commission");warehouseAccess(w,actor,found(w.documents,c.invoiceId,"Invoice").warehouseId);if(D(c.released).lte(c.paid))throw new Error("There is no released unpaid commission to approve.");c.approved=true;}result=ids[0];message="Commission approved for payroll.";break;}
 case "create_payroll":result=payroll(w,p);message="Payroll calculated using prototype rules.";break;
 case "update_payroll":{const pr=found(w.payrolls,s(p,"id"),"Payroll");const status=z.enum(["reviewed","approved","paid"]).parse(p.status);const expected:Record<string,string>={draft:"reviewed",reviewed:"approved",approved:"paid"};if(expected[pr.status]!==status)throw new Error("Invalid payroll transition.");requireOpen(w,pr.date);for(const l of pr.lines)for(const key of l.commissionIds){const c=found(w.commissions,key,"Commission");if(status!=="paid"&&(!c.approved||D(l.commissionAmounts[key]).gt(D(c.released).minus(c.paid))))throw new Error("Commission changed since this payroll was calculated. Reconcile the run before approval.");}
 if(status==="approved"){const salary=sum(pr.lines.map(l=>D(l.basic).plus(l.allowance).plus(l.employerEobi)));const comm=sum(pr.lines.map(l=>l.commission));const statutory=sum(pr.lines.map(l=>D(l.employeeEobi).plus(l.employerEobi).plus(l.incomeTax).plus(l.deduction)));postJournal(w,`${pr.id}:approve`,pr.number,[jl("5200",money(salary)),jl("2200",money(comm)),jl("2300",0,pr.total),jl("2400",0,money(statutory))],pr.date);}
 if(status==="paid"){postJournal(w,`${pr.id}:paid`,`${pr.number} · simulated salary payment`,[jl("2300",pr.total),jl("1000",0,pr.total)],pr.date);for(const l of pr.lines)for(const key of l.commissionIds){const c=found(w.commissions,key,"Commission");const amount=l.commissionAmounts[key];c.paid=money(D(c.paid).plus(amount));w.commissionMovements.push({id:id(),commissionId:key,sourceId:pr.id,date:pr.date,type:"paid",amount,note:"Simulated payroll payment; no bank transmission"});}}pr.status=status;result=pr.id;message=`Payroll ${status}. Bank transmission is simulated.`;break;}
 case "create_shipment":{const doc=found(w.documents,s(p,"documentId"),"Purchase document");if(!["goods_receipt","supplier_invoice"].includes(doc.kind)||doc.status!=="submitted")throw new Error("Choose a submitted receipt or supplier bill.");warehouseAccess(w,actor,doc.warehouseId);const shipment={id:id(),number:`SHP-2026-${String(w.shipments.length+1).padStart(3,"0")}`,supplierId:doc.partyId,documentId:doc.id,origin:s(p,"origin","Shenzhen"),port:s(p,"port","Karachi"),container:s(p,"container",""),gdNumber:s(p,"gdNumber",""),eta:date(p.eta??today()),status:"received" as const,costs:[],allocations:[]};w.shipments.push(shipment);result=shipment.id;break;}
 case "add_shipment_cost":{const sh=found(w.shipments,s(p,"id"),"Shipment");const cost=z.object({label:z.string().min(1).max(100),amount:pos,classification:z.enum(["inventory","recoverable_tax","deposit","expense"]),basis:z.enum(["value","quantity","weight","volume"])}).parse(p);sh.costs.push({...cost,id:id(),allocated:false});sh.status="received";result=sh.id;break;}
 case "allocate_shipment":{const sh=found(w.shipments,s(p,"id"),"Shipment");const doc=found(w.documents,sh.documentId,"Source receipt");const d=date(p.date??today());requireOpen(w,d);warehouseAccess(w,actor,doc.warehouseId);const pending=sh.costs.filter(c=>!c.allocated);if(!pending.length)throw new Error("All shipment costs are already allocated.");const journal:JournalLine[]=[];for(const cost of pending){if(cost.classification==="inventory"){const weights=doc.lines.map(l=>{const item=found(w.items,l.itemId,"Item");return money(cost.basis==="value"?lineTotal(l):D(l.quantity).mul(cost.basis==="weight"?item.weight:cost.basis==="volume"?item.volume:1));});const portions=allocate(cost.amount,weights);let inventory=D(0),cogs=D(0);doc.lines.forEach((l,i)=>{const receivedValue=D(l.cost).mul(l.quantity);const movesAfterReceipt=w.stockMoves.filter(m=>m.itemId===l.itemId&&m.warehouseId===doc.warehouseId&&m.date>=doc.date&&D(m.quantity).lt(0));const sold=D.min(l.quantity,sum(movesAfterReceipt.map(m=>D(m.quantity).abs())));const current=stock(w,l.itemId,doc.warehouseId);const onHand=D.min(D(l.quantity).minus(sold),current.quantity);const stockPart=D(portions[i]).mul(onHand).div(l.quantity).toDecimalPlaces(4);const soldPart=D(portions[i]).minus(stockPart);inventory=inventory.plus(stockPart);cogs=cogs.plus(soldPart);move(w,l.itemId,doc.warehouseId,"0",money(stockPart),`${sh.id}:${cost.id}`,d,"landed_cost");sh.allocations.push({costId:cost.id,itemId:l.itemId,amount:portions[i]});void receivedValue;});journal.push(jl("1200",money(inventory)),jl("5000",money(cogs)));}else journal.push(jl(cost.classification==="recoverable_tax"?"1300":cost.classification==="deposit"?"1400":"5300",cost.amount));cost.allocated=true;}
 journal.push(jl("2000",0,money(sum(pending.map(c=>c.amount)))));postJournal(w,`${sh.id}:${pending.map(c=>c.id).join(":")}`,`Landed costs · ${sh.number}`,journal,d);sh.status="costed";result=sh.id;message="Costs allocated. Inventory, COGS and supplier liability updated.";break;}
 case "stock_transfer":{const item=s(p,"itemId"),from=s(p,"from"),to=s(p,"to");if(from===to)throw new Error("Choose two different warehouses.");warehouseAccess(w,actor,from);warehouseAccess(w,actor,to);const qty=pos.parse(p.quantity);const d=date(p.date??today());requireOpen(w,d);const value=D(stock(w,item,from).average).mul(qty).toDecimalPlaces(4);result=id();move(w,item,from,money(D(qty).negated()),money(value.negated()),result,d,"transfer_out");move(w,item,to,qty,money(value),result,d,"transfer_in");message=`Moved ${D(qty).toString()} ${found(w.items,item,"Product").name} from ${found(w.warehouses,from,"Warehouse").name} to ${found(w.warehouses,to,"Warehouse").name}.`;break;}
 case "stock_adjust":{const item=s(p,"itemId"),warehouse=s(p,"warehouseId");warehouseAccess(w,actor,warehouse);found(w.items,item,"Product");const qty=decimal.parse(p.quantity);if(D(qty).eq(0))throw new Error("Enter a non-zero adjustment.");const d=date(p.date??today());requireOpen(w,d);const reason=s(p,"reason");if(!reason.trim())throw new Error("Adjustment reason is required.");const cost=nonneg.parse(p.cost??stock(w,item,warehouse).average);const value=D(qty).mul(cost).toDecimalPlaces(4);result=id();move(w,item,warehouse,qty,money(value),result,d,"adjustment");postJournal(w,result,reason,value.gte(0)?[jl("1200",money(value)),jl("5300",0,money(value))]:[jl("5300",money(value.negated())),jl("1200",0,money(value.negated()))],d);break;}
 case "bulk_stock_increase":{
  const input=z.object({warehouseId:z.string(),date:z.iso.date(),purpose:z.enum(["opening_stock","count_correction"]),reason:z.string().trim().min(1).max(2000),lines:z.array(z.object({itemId:z.string(),quantity:pos,cost:pos})).min(1).max(500)}).parse(p);
  warehouseAccess(w,actor,input.warehouseId);requireOpen(w,input.date);
  if(new Set(input.lines.map(line=>line.itemId)).size!==input.lines.length)throw new Error("Each product can appear only once in a stock increase.");
  const rows=input.lines.map(line=>{found(w.items,line.itemId,"Product");const value=money(D(line.quantity).mul(line.cost));if(D(value).lte(0))throw new Error("Each added stock line must have a positive value.");return {...line,value};});
  result=id();
  for(const row of rows)move(w,row.itemId,input.warehouseId,money(row.quantity),row.value,result,input.date,"adjustment");
  const total=money(sum(rows.map(row=>row.value)));
  postJournal(w,result,input.reason,[jl("1200",total),jl(input.purpose==="opening_stock"?"3000":"5300",0,total)],input.date);
  message=`Increased stock for ${rows.length} product${rows.length===1?"":"s"}. Inventory value and journal updated.`;
  break;
 }
 case "create_journal":{const rows=z.array(z.object({account:z.string(),debit:nonneg,credit:nonneg})).min(2).parse(p.lines);result=id();postJournal(w,result,s(p,"memo"),rows,date(p.date??today()));message="Balanced journal posted.";break;}
 case "reverse_journal":{const j=found(w.journals,s(p,"id"),"Journal");if(w.journals.some(x=>x.reversalOf===j.id))throw new Error("Journal is already reversed.");if(w.documents.some(d=>d.id===j.sourceId)||j.sourceId.includes(":")||j.memo.startsWith("Opening"))throw new Error("Use the source document's correction workflow for operational journals.");result=id();postJournal(w,result,`Reversal · ${j.number}`,j.lines.map(l=>jl(l.account,l.credit,l.debit)),date(p.date??today()),j.id);break;}
 case "set_period":{const month=z.string().regex(/^\d{4}-(0[1-9]|1[0-2])$/).parse(p.month);const locked=z.boolean().parse(p.locked);if(!locked&&actor.role!=="Owner")throw new Error("Only the owner can reopen an accounting period.");let period=w.periods.find(x=>x.month===month);if(!period){period={month,locked};w.periods.push(period)}else period.locked=locked;result=month;message=`Period ${locked?"locked":"reopened"}.`;break;}
 case "save_party":{const input=z.object({id:z.string().optional(),name:z.string().min(2).max(120),type:z.enum(["customer","supplier"]),city:z.string().max(120),email:z.union([z.email(),z.literal("")]),taxId:z.string().max(100),registered:z.boolean(),creditLimit:nonneg,terms:z.coerce.number().int().min(0).max(365),customerClass:z.string().max(100)}).parse(p);const record={...input,id:input.id??id()};const index=w.parties.findIndex(x=>x.id===record.id);if(index>=0){if(w.parties[index].type!==record.type)throw new Error("A party's type cannot be changed.");w.parties[index]=record;}else w.parties.push(record);result=record.id;break;}
 case "save_item":{const input=z.object({id:z.string().optional(),sku:z.string().min(1).max(50),name:z.string().min(2).max(120),category:z.string().max(100),hsCode:z.string().max(30),unit:z.string().max(20),price:nonneg,cost:nonneg,weight:nonneg,volume:nonneg,reorderLevel:z.coerce.number().int().min(0)}).parse(p);if(w.items.some(i=>i.sku===input.sku&&i.id!==input.id))throw new Error("SKU already exists.");const item={...input,id:input.id??id()};const index=w.items.findIndex(i=>i.id===item.id);if(index>=0)w.items[index]=item;else w.items.push(item);result=item.id;break;}
 case "save_employee":{const input=z.object({id:z.string().optional(),name:z.string().min(2).max(100),role:z.string().max(100),territory:z.string().max(100),parentId:z.string().optional(),salary:nonneg,allowance:nonneg,deduction:nonneg,attendance:z.coerce.number().min(0).max(30),active:z.boolean()}).parse(p);const employee={...input,id:input.id??id()};if(employee.parentId){let parent=found(w.employees,employee.parentId,"Manager");const seen=new Set([employee.id]);while(parent){if(seen.has(parent.id))throw new Error("The sales hierarchy cannot contain a cycle.");seen.add(parent.id);if(!parent.parentId)break;parent=found(w.employees,parent.parentId,"Manager");}}const index=w.employees.findIndex(e=>e.id===employee.id);if(index>=0)w.employees[index]=employee;else w.employees.push(employee);result=employee.id;break;}
 case "save_plan":{const plan=z.object({id:z.string().optional(),name:z.string().min(2).max(100),effectiveFrom:z.iso.date(),effectiveTo:z.iso.date(),type:z.enum(["flat","category","customer_class","per_unit","tiered"]),rate:nonneg,categoryRates:z.record(z.string(),pct),classRates:z.record(z.string(),pct),tiers:z.array(z.object({threshold:nonneg,rate:pct})).min(1),target:nonneg,multiplier:pos}).parse(p);if(plan.effectiveTo<plan.effectiveFrom)throw new Error("Plan dates are invalid.");if(w.plans.some(x=>x.id!==plan.id&&x.effectiveFrom<=plan.effectiveTo&&x.effectiveTo>=plan.effectiveFrom))throw new Error("Commission plan dates overlap.");const record={...plan,id:plan.id??id()};const index=w.plans.findIndex(x=>x.id===record.id);if(index>=0)w.plans[index]=record;else w.plans.push(record);result=record.id;break;}
 case "save_settings":{const input=z.object({company:z.object({name:z.string().min(2).max(120),taxId:z.string().max(100),address:z.string().max(500),currency:z.literal("PKR"),logo:z.string().max(3)}),settings:z.object({taxRate:pct,employerEobi:pct,employeeEobi:pct,eobiBase:nonneg,incomeTaxRate:pct,numbering:z.string().min(1).max(10),approvalLimit:nonneg})}).parse(p);w.company=input.company;w.settings=input.settings;result=w.tenantId;break;}
 case "bank_import":{const lines=z.array(z.object({date:z.iso.date(),description:z.string().min(1).max(200),amount:decimal})).min(1).max(1000).parse(p.lines);for(const line of lines){if(w.bankLines.some(x=>x.date===line.date&&x.description===line.description&&D(x.amount).eq(line.amount)))continue;w.bankLines.push({...line,id:id(),amount:money(line.amount),matchedJournalId:null});}result=w.bankLines.at(-1)?.id??"";break;}
 case "bank_match":{const line=found(w.bankLines,s(p,"id"),"Statement row");if(line.matchedJournalId)throw new Error("Statement row is already matched.");const journal=found(w.journals,s(p,"journalId"),"Journal");if(w.bankLines.some(l=>l.matchedJournalId===journal.id))throw new Error("Journal is already matched.");const amount=sum(journal.lines.filter(l=>l.account==="1000").map(l=>D(l.debit).minus(l.credit)));if(!amount.eq(line.amount))throw new Error("Statement amount must match the bank journal amount.");line.matchedJournalId=journal.id;result=line.id;break;}
 case "follow_up":{result=s(p,"partyId");found(w.parties,result,"Customer");const note=s(p,"note");const next=date(p.nextDate);if(!note.trim())throw new Error("Enter a follow-up note.");message=`${note} · Next action ${next}`;break;}
 case "import_records":{const kind=z.enum(["customers","suppliers","items","attendance"]).parse(p.kind);const rows=z.array(z.record(z.string(),z.unknown())).min(1).max(1000).parse(p.rows);for(const row of rows){if(kind==="attendance"){const e=w.employees.find(e=>e.id===row.employeeId||e.name===row.name);if(!e)throw new Error(`Employee ${row.name??row.employeeId} not found.`);e.attendance=z.coerce.number().min(0).max(30).parse(row.attendance);}else{const type=kind==="items"?"save_item":"save_party";const data=kind==="items"?{category:"General",hsCode:"",unit:"pcs",price:"0",cost:"0",weight:"1",volume:"1",reorderLevel:0,...row}:{city:"",email:"",taxId:"",registered:false,creditLimit:"500000",terms:30,customerClass:"Retailer",...row,type:kind==="customers"?"customer":"supplier"};const duplicate=kind==="items"?w.items.some(i=>i.sku===row.sku):w.parties.some(i=>i.name===row.name);if(duplicate)throw new Error(`Duplicate record: ${row.name??row.sku}.`);const applied=execute(w,{type,payload:data,idempotencyKey:`${command.idempotencyKey}:${w.items.length}:${w.parties.length}`},{...actor,role:"Owner"});Object.assign(w,applied.workspace);}}result=w.tenantId;message=`${rows.length} records imported.`;break;}
 }
 w.operations.push(command.idempotencyKey);w.revision=input.revision+1;w.audit.push({id:id(),date:new Date().toISOString(),actor:actor.name,role:actor.role,action:command.type,sourceId:result,detail:message});return {workspace:w,recordId:result,message};
}
